# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  solution: 'src\'
  buildPlatform: Any CPU
  buildConfiguration: Release
  versionPrefix: 0.0.1

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/Yxney.IO.HashPath
    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 7.0.x
       
#    - name: 'Show dotnet info'
#      run: dotnet --info

    - name: 'Show dotnet version'
      run: dotnet --version
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore  

    - name: Test
      run: dotnet test --no-build --verbosity normal      

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/coverage.cobertura.xml